[build]
  # El comando para construir la app
  command = "npm run build"
  
  # El directorio que Netlify debe publicar para Next.js
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_DOMAIN = "https://pos-nexjs-front.netlify.app"
